name: Run Notebook Tests

on:
  workflow_call:
    inputs:
      python_version:
        description: "Determines which Python version to use"
        type: string
        required: true

env:
  PY_COLORS: 1

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python ${{ inputs.python_version }}
      uses: ./.github/actions/python
      with:
        python_version: ${{ inputs.python_version }}
    - name: Cache Tox Directory for Tests
      uses: actions/cache@v3
      with:
        key: tox-${{ github.ref }}-${{ runner.os }}-${{ hashFiles('tox.ini', 'requirements.txt') }}-${{ inputs.python_version }}
        path: .tox
    - name: Cache Pytest Cache Directory
      uses: actions/cache@v3
      with:
        key: pytest-cache-${{ github.ref }}-${{ runner.os }}-${{ inputs.python_version }}
        path: .tox/tests/.pytest_cache
    - name: Set up memcached
      uses: niden/actions-memcached@v7
    - name: Test Group 1
      run: tox -e tests -- --slow-tests --splits 3 --group 1 --splitting-algorithm least_duration
      if: inputs.tests_to_run == 'group1'
    - name: Test Group 2
      run: tox -e tests -- --slow-tests --splits 3 --group 2 --splitting-algorithm least_duration
      if: inputs.tests_to_run == 'group2'
    - name: Test Group 3
      run: tox -e tests -- --slow-tests --splits 3 --group 3 --splitting-algorithm least_duration
      if: inputs.tests_to_run == 'group3'
