name: 'Close stale issues and PRs by externals'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/stale@v9
        with:
          only-labels: 'awaiting-reply'
          days-before-stale: 30
          days-before-close: 7
          exempt-all-assignees: true
          exempt-draft-pr: true
          stale-issue-message: 'Stale issue: awaiting OPs reply for 30 days'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          stale-issue-label: 'stale'
          stale-pr-message: 'Stale PR: awaiting OPs reply for 30 days'
          close-pr-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          stale-pr-label: 'stale'
